import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';
import { toast } from 'sonner';
import { formatCurrency, DEFAULT_SYSTEM_CURRENCY } from './currency';

interface OrderItem {
  quantity: number;
  product?: {
    name: string;
  };
}

interface Order {
  order_code: string;
  created_at: string;
  payment_method?: string;
  total_amount: number;
  order_items?: OrderItem[];
}

interface ShiftReportData {
  session: {
    id: string;
    opened_at: string;
    closed_at?: string | null;
    opening_cash: number;
    total_sales: number;
    total_orders: number;
    shop?: {
      name: string;
      address?: string;
    };
    user?: {
      name: string;
    };
  };
  shiftOrders: Order[];
  closingCash: number;
  expectedCash: number;
  description?: string;
  currency?: string;
}

interface jsPDFWithAutoTable extends jsPDF {
  lastAutoTable: {
    finalY: number;
  };
}

const createShiftReportDoc = ({
  session,
  shiftOrders,
  closingCash,
  expectedCash,
  description,
  currency = DEFAULT_SYSTEM_CURRENCY
}: ShiftReportData) => {
  const doc = new jsPDF();
  const shopName = session.shop?.name || 'Shop Name';
  const staffName = session.user?.name || 'Unknown Staff';
  const shopAddress = session.shop?.address || '';
  const difference = closingCash - expectedCash;

  // Header Section
  doc.setFontSize(22);
  doc.text(shopName, 14, 20);

  doc.setFontSize(10);
  if (shopAddress) {
    doc.text(shopAddress, 14, 26);
  }

  doc.line(14, 30, 196, 30); // Horizontal line

  // Metadata Section
  doc.setFontSize(12);
  doc.text("End of Shift Report", 14, 40);

  doc.setFontSize(10);
  const metadata = [
    [`Report ID:`, session.id.slice(0, 8).toUpperCase()],
    [`Generated By:`, staffName],
    [`Date Generated:`, format(new Date(), 'PPpp')],
    [`Shift Opened:`, format(new Date(session.opened_at), 'PPpp')],
    [`Shift Closed:`, session.closed_at ? format(new Date(session.closed_at), 'PPpp') : 'Active'],
  ];

  let metaY = 48;
  metadata.forEach(([label, value]) => {
    doc.setFont("helvetica", "bold");
    doc.text(label as string, 14, metaY);
    doc.setFont("helvetica", "normal");
    doc.text(value as string, 50, metaY);
    metaY += 6;
  });

  // Financial Summary Table
  autoTable(doc, {
    startY: metaY + 5,
    head: [['Financial Summary', 'Amount']],
    body: [
      ['Opening Cash', formatCurrency(session.opening_cash, currency)],
      ['Total Sales', formatCurrency(session.total_sales, currency)],
      ['Expected Cash', formatCurrency(expectedCash, currency)],
      ['Actual Cash Count', formatCurrency(closingCash, currency)],
      ['Variance', formatCurrency(difference, currency)],
    ],
    theme: 'grid',
    headStyles: { fillColor: [66, 66, 66] },
  });

  // Detailed Orders Table
  if (shiftOrders && shiftOrders.length > 0) {
    const finalY = (doc as unknown as jsPDFWithAutoTable).lastAutoTable.finalY || 100;
    doc.setFontSize(12);
    doc.text("Detailed Order History", 14, finalY + 15);

    autoTable(doc, {
      startY: finalY + 20,
      head: [['Order #', 'Time', 'Payment', 'Total']],
      body: shiftOrders.map(order =>
        [`${order.order_code}`, format(new Date(order.created_at), 'HH:mm'), order.payment_method || '-', formatCurrency(Number(order.total_amount), currency)]
      ),
      theme: 'grid',
      headStyles: { fillColor: [66, 66, 66] },
      styles: { fontSize: 9, cellPadding: 3 },
    });
  }

  // Notes Section
  if (description) {
    const finalY = (doc as unknown as jsPDFWithAutoTable).lastAutoTable.finalY || 150;
    doc.setFontSize(12);
    doc.text("Shift Notes", 14, finalY + 15);
    doc.setFontSize(10);
    const splitNotes = doc.splitTextToSize(description, 180);
    doc.text(splitNotes, 14, finalY + 22);
  }

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(`BakeSync POS Report - ${shopName} - Staff: ${staffName} - Page ${i} of ${pageCount}`, 14, doc.internal.pageSize.height - 10);
  }

  return doc;
};

export const generateShiftReportPDF = (data: ShiftReportData) => {
  try {
    const doc = createShiftReportDoc(data);
    doc.save(`Shift_Report_${data.session.shop?.name.replace(/\s+/g, '_')}_${format(new Date(), 'yyyyMMdd')}.pdf`);
    toast.success("PDF exported successfully");
    return true;
  } catch (error) {
    console.error("PDF Gen Error:", error);
    toast.error("Failed to generate PDF");
    return false;
  }
};

export const generateShiftReportBase64 = (data: ShiftReportData) => {
  try {
    const doc = createShiftReportDoc(data);
    return doc.output('datauristring').split(',')[1]; // Return base64 content only (remove "data:application/pdf;base64,")
  } catch (error) {
    console.error("PDF Base64 Gen Error:", error);
    return null;
  }
};
